### ISSUE TITLE
ELK with APM agent

### ISSUE THREAD

**Issue by prabaprakash** [prabaprakash/Docker-n-Traefik#3]
ELK
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

Elasticsearch
docker run -p 9200:9200 -p 9300:9300 --name=elasticsearch -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.9.1

Kibana
docker run --name=kibana --link elasticsearch:elasticsearch -p 5601:5601 docker.elastic.co/kibana/kibana:7.9.1

**Comment by prabaprakash** [comment]
APM
curl -L -O https://raw.githubusercontent.com/elastic/apm-server/7.9/apm-server.docker.yml

apm-server.yml
```
apm config
apm-server:
  host: "0.0.0.0:8200"
  concurrent_requests: 5
  rum:
    enabled: false
  kibana:
    enabled: true
    host: "http://kibana:5601"
queue.mem.events: 4096
max_procs: 4

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana.host: "kibana:5601"

logging.level: info
logging.to_files: false
```
docker run -d \
 -p 8200:8200 \
  --name=apm-server \
  --user=apm-server \
  --volume="$(pwd)/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro" \
  --link elasticsearch:elasticsearch \
  --link kibana:kibana \
  docker.elastic.co/apm/apm-server:7.9.1
