### ISSUE TITLE
Configuring Prometheus alert

### ISSUE THREAD

**Issue by prabaprakash** [prabaprakash/Docker-n-Traefik#5]

**Comment by prabaprakash** [comment]
prometheus.yml
```
global:
  scrape_interval: 15s

rule_files:
  - '/etc/prometheus/alert.rules'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - 192.xxx.xxx.xxx:9093
scrape_configs:
- job_name: node
  static_configs:
  - targets: ['192.168.1.5:80']

```
alert.rules
```
groups:
 - name: Service-Alerts
   rules:
   - alert: PostgresAlert
     expr: postgres_error_counter > 10
     for: 1m
     annotations:
       title: "{{ $labels.environment }} Server: *PostgresAlert*"
       description: "Postgres has too many connection errors (> 10)\n VALUE = {{ $value }}\n\n"
     labels:
       severity: 'error'
```
alert_manager.yml
```
global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#general'
        send_resolved: true
        title: '{{ .CommonAnnotations.title }}'
        text: '{{ .CommonAnnotations.description }}'
```
docker run commands
```
docker run -it -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml \
  -v $PWD/alert.rules:/etc/prometheus/alert.rules \
  -p 9090:9090 prom/prometheus

docker run -it -v $PWD/alertmanager.yml:/etc/alertmanager/alertmanager.yml -p 9093:9093 -it prom/alertmanager
```
